### ISSUE TITLE
Verilator now has built in support for Python

### ISSUE THREAD

**Issue by BracketMaster** [csail-csg/pyverilator#1]
You guys may wanna check this out:
https://github.com/patstew/verilator/tree/python/examples/make_python
Verilator now has built in support for Python. I think its gonna get merged into master in the next release.

**Comment by BracketMaster** [comment]
In addition, cocotb Python also has support for Verilator.

**Comment by acw1251** [comment]
Thanks for the info! I'll have to check them out.
