### ISSUE TITLE
No tags for more recent versions

### ISSUE THREAD

**Issue by nickfraser** [csail-csg/pyverilator#12]
I noticed that you don't have pypi releases or github tags any versions beyond 0.1.0, but when I install the latest from the master branch from github with pip, I get that the installed version is 0.7.0... Do you plan on doing another release (as either a tag or on pypi) with newer versions of the code.

I ask because, this project is a dependency of my project (https://github.com/Xilinx/logicnets), but it also depends on more recent features than what is available in pypi. It would be nice to be able to specify that dependency in terms of a version number, but I cannot do that right now.

Do you plan on making more releases for this project?

**Comment by acw1251** [comment]
We'll get a new release on pypi soon. I'll let you know when its ready.

**Comment by threonorm** [comment]
0.7.0 should be in pypi now

**Comment by acw1251** [comment]
And I just added a new tag for 0.7.0 on github.

**Comment by nickfraser** [comment]
Awesome - thanks!
